### ISSUE TITLE
404 on front page

### ISSUE THREAD

**Issue by craigralston** [ryelle/Anadama-React#1]
I was getting a 404 from `/wp-json/wp/v2/terms/category/?page=1&hide_empty=true&per_page=10` before I made any file changes.

Updating this line https://github.com/ryelle/Anadama-React/blob/master/js/utils/api.js#L46 from `let url = AnadamaSettings.URL.root + '/terms/category/';` to `let url = AnadamaSettings.URL.root + '/categories/';` resolved it for me. Could totally just be something on my end - I am running core trunk and WP REST API v 2.0-beta9.

Disclaimer: A lot of this is new to me (React, WP REST API).

**Comment by peepshow** [comment]
@Lingo36 Ditto, same issue for me. Quick fix of dropping **~~/terms/~~** worked for me also, I haven't had a chance to look into the what, how, and why, or find if there's a "best solution". 
For now this is sweet for having a jam with the theme. Cheers  

BTW if it helps to know, I'm running WP locally on Mac, using a native LAMP with a dynamic/automated VirtualHosts config. 
- PHP 5.5.29
- MySQL - 5.5.27 
- WP Core – 4.4  
- WP REST – API Version 2.0-beta9
- WP REST API Menus – Version 1.2.0

**Comment by ryelle** [comment]
Looks like a change in WP API 2.0-beta9 (see [the first item in the changelog](https://make.wordpress.org/core/2015/12/11/wp-rest-api-version-2-0-beta-9/)). I was still running 2.0-beta7. Pushing a fix soon -- you'll need to re-run `gulp` to rebuild after updating.
