### ISSUE TITLE
app.js = 1.24 MB

### ISSUE THREAD

**Issue by unremarkablegarden** [ryelle/Anadama-React#6]
Does the app.js *really* have to be this enormous? Trying to enable webpack.optimize.UglifyJsPlugin() but I can't get it to work. Any tips?

**Comment by ryelle** [comment]
This was never meant to be anything run in a production environment, it's just an experiment (maybe check out [Foxhound](https://github.com/ryelle/Foxhound), which is already being used on [a real website](https://ryelle.codes)?). Plus, I'm not sure what you _were_ trying, so I can't really answer that question.

That said, I've updated the config to add minification & to use the production React library, so you can see how that looks in master now.
