### ISSUE TITLE
How to deploy this theme to wordpress

### ISSUE THREAD

**Issue by murtdagi** [ryelle/Anadama-React#7]
Hi, I have cloned your repository locally and have followed the steps as outlined. All went well.
Now i would like to know, how and in what structure shall we add the built files to wordpress and at what location in my wordpress install?

I am trying to use react for a wordpress website and i am not sure how to use react with wordpress. Would really appreciate any help with this.

Thanks

**Comment by ryelle** [comment]
Hi there! Thanks for trying Anandama. It's a WordPress theme, so it should live in your `wp-content/themes/` directory. As soon as you build the files, it should come up in the themes list in the WordPress dashboard (Appearance > Themes).

**Comment by murtdagi** [comment]
Yes, that worked. Thanks a lot for your help and quick response.
